name: 'Custom GitHub Action'
description: 'takes number and retrunthe squared number'
inputs:
   num:1
   required: true
   default: "1"
outputs:
   num_squared:
    value: ${{ }}
runs:
    using: 'composite'
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependecies
        run: pip install -r requirements.txt
        shell: bash
      - name: Pass inputs to shell
        run: 
          echo "INPUT_NUM=${inputs.num}}" >> $GITHUB_ENV
        shell: bash
      - name: Fetch the number's square
        id: get-square
        run: python src/get_num_square.py
        shell: bash
