name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: return the number square
    steps:
    -name: Checkout
     uses: actions/checkout@v4
    -name: Fetch num squared
     id: get_square
     uses: ./
     with:
       num: 11
   -name: print the square
    run: echo "${{ steps.get_square.outputs.num.squared }}"
